### ISSUE TITLE
Feature - Migrate components from corporate-ui v3.x

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui-dev#115]
**Is your feature request related to a problem? Please describe.**
Currently there are components in version 3.x that should be migrated into the new 4.x version of corporate-ui-dev 

**compare it to the current solution in 3.x**
What is missing(attributes)?
What have been added?
Should we remove it?

**Describe the solution you'd like**
A working component in version 4.x of corporate-ui

List: 

**c-corporate-header**
- [ ] #93 Shortname
- [ ] #116 Dealername
- [ ] #124 Scania icon sticky nav
- [ ] #121 initial unit-test
- [ ] #121 initial e2e test
- [ ] Responsive
- [ ] App/public (consider)

**c-main-navigation**
- [ ] #117 More solution
- [ ] #122 Sticky nav
- [ ] #121 initial unit-test
- [ ] #121 initial e2e test

**c-corporate-footer**
- [ ] #101 Remove drop
- [ ] #121 initial unit-test
- [ ] #121 initial e2e test

**Social-media**
- [ ] #121 initial unit-test
- [ ] #121 initial e2e test

 **fullscreen** (consider)
- [ ] initial unit-test
- [ ] initial e2e test

**main-hero** (consider)
**Login** (consider)
**dashboard** (consider)
**Teaser** (consider)
**Alert** (consider)
**Modal** (consider)
**Map** (consider)
**Map-card** (consider)
