### ISSUE TITLE
Shipping list - 4.0.0-beta.4

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui-dev#241]
### Shipping list for version 4.0.0-beta.4

**Components**
- [x] Enable source mapping #224 
- [x] Css buttons id renderder twice scania/scania-theme#44

**Core**
- [x] Upgrade to stencil one #216
- [x] Refactor the store structure #178 
- [x] Intial load is delayed using angular #184 

**Documentation**
- [x] Remove storybook and replace with #217  
- [x] Move storybook from local setup #233

**Comment by mmexvr** [comment]
#244
